minimum_pre_commit_version: 1.15.0
default_language_version:
    python: python3.6
repos:
    -
        repo: 'https://github.com/ambv/black'
        rev: 19.3b0
        hooks:
            - id: black
              name: Black
              exclude: templates/
              args: ['--safe', '-l 100', '.']

    -
        repo: 'https://github.com/timothycrosley/isort.git'
        rev: 4.3.21
        hooks:
            - id: isort
              name: Sort Imports
              exclude: templates/
              args: ['-rc', '-m 3', '-tc', '-w 100', '-e']
    -
        repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.0.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: debug-statements
        -   id: check-merge-conflict
        -   id: check-docstring-first
            language_version: python3.6
